### ISSUE TITLE
Empty only empties the calendar month view but not the events

### ISSUE THREAD

**Issue by djcaesar9114** [brospars/simple-calendar#44]
Hello,
First of all thanks for your work.
When I write this:
```
container.empty().data('plugin_simpleCalendar', null).simpleCalendar({
    displayEvent: true,
    events: events
  });
```
It refreshed the events in the month view (the blue dots appear on the correct dates) but the previous events remain the same: if I click on a date when there was an event, I can still see it in the list of the events of the day.

I tried to solve this issue: https://stackoverflow.com/questions/69754113/is-there-a-way-i-can-empty-my-object-to-make-new-dates-able-to-be-inserted-ont/69755768#69755768

**Comment by brospars** [comment]
Hello,
First of all thank you for reporting this issue and helping on stackoverflow. 

The problem is that `.empty()` doesn't remove delegated events from the container (e.g. [those events](https://github.com/brospars/simple-calendar/blob/0af2a9fa5c764e3ce437c6b4dbd2ff89f66daac3/src/jquery.simple-calendar.js#L176)) so you need to call `.off()` in addition of `.empty()`.

I fixed it in the commit mentioned above. I have also added a [method to set events](https://github.com/brospars/simple-calendar/blob/998b930194d323049bdee9f03ff76e2567c43d82/src/jquery.simple-calendar.js#L223) without the need to reset the whole calendar.
